defaults:
  - env: default
  - ppo: default
  - d3qn: default
  - td3: default

training:
  num_episodes: 500
  batch_size: 256
  seed: 42
  # seeds:
  #   - 0
  #   - 1
  #   - 7
  #   - 13
  #   - 17
  #   - 23
  #   - 29
  #   - 31
  #   - 37
  #   - 41
  #   - 42
  #   - 43
  #   - 47
  #   - 48
  #   - 56
  #   - 61
  #   - 84
  #   - 100
  #   - 250
  #   - 512

