defaults:
  - env: default
  - ppo: default
  - td3: default
  - _self_  # Allows this file to add/override values.

training:
  seed: 42
wandb:
  use: True
  project: "hetnet-rl-project-multirun"
  group: "PPO-Baseline-Sweep"
  name: "seed-${training.seed}"
